services:
  back:
    build: ./back
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: auto-scheduler
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_DB: auto-scheduler
    ports:
      - '3000:3000'
    networks:
      - default
      - db
    depends_on:
      - mongo
      - neo4j
  
  front:
    build: ./front
    ports:
      - '8080:3000'
    networks:
      - default
    depends_on:
      - back
  
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env.mongo
    networks:
      - db

  neo4j:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j-data:/data
    env_file:
      - .env.neo4j
    networks:
      - db

volumes:
  mongo-data:
  neo4j-data:

networks:
  db: