export const DEFAULT_TARGET_HOURS = 24;
export const DEFAULT_REDUCE_DAYS = true;
export const DEFAULT_PRIORITIZE_UNLOCKS = true;
export const DEFAULT_DISTANCE = 30;
export const DEFAULT_RETURNED_AMOUNT = 10;

export enum SCHEDULE_ALGORITHM {
    COURSE_GREEDY='COURSE_GREEDY',
    TIME_GREEDY='TIME_GREEDY',
    GENETIC='GENETIC',
}