const OK = 200;
const CREATED = 201;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const TIMEOUT = 408;
const CONFLICT = 409;
const INTERNAL_ERROR = 500;
const SERVICE_UNAVAILABLE = 503;
const TIMEOUT_ERROR = "ECONNABORTED";
const CONNECTION_ERROR = "ERR_NETWORK";

export { OK, CREATED, NO_CONTENT, BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, TIMEOUT, CONFLICT, INTERNAL_ERROR, SERVICE_UNAVAILABLE, TIMEOUT_ERROR, CONNECTION_ERROR };
